# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-22 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FyyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BigIntegerField(default=0)),
                ('des', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
                ('p_id', models.BigIntegerField(default=0)),
                ('p_ids', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('permission', models.CharField(max_length=255)),
                ('avaliable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'fyy_permission',
            },
        ),
        migrations.CreateModel(
            name='FyyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('create_id', models.BigIntegerField(default=0)),
                ('crt_time', models.DateTimeField()),
                ('update_id', models.BigIntegerField(default=0)),
                ('update_time', models.DateTimeField()),
                ('remark', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'fyy_role',
            },
        ),
        migrations.CreateModel(
            name='FyyRolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField(default=0)),
                ('permission_id', models.BigIntegerField(default=0)),
                ('create_id', models.BigIntegerField(default=0)),
                ('crt_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'fyy_role_permission',
            },
        ),
        migrations.CreateModel(
            name='FyyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('sex', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'fyy_users',
            },
        ),
        migrations.CreateModel(
            name='FyyUsersRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('role_id', models.BigIntegerField(default=0)),
                ('create_id', models.BigIntegerField(default=0)),
                ('crt_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'fyy_users_role',
            },
        ),
    ]
